# Jazztronauts Localization: Russian

#==============================================================================
#	CATS
#==============================================================================
jazz.cat.bartender=Бармен
jazz.cat.singer=Певец
jazz.cat.pianist=Пианистка
jazz.cat.cellist=Виолончелист
jazz.cat.unknown=???
jazz.cat.ash=Эш
#==============================================================================
#	WEAPONS
#==============================================================================
jazz.weapon.category=Джазтронавты
#Prop Snatcher
jazz.weapon.snatcher=Похититель пропов
jazz.weapon.snatcher.upgrade.cone=Круг-прицел
jazz.weapon.snatcher.upgrade.cone.desc=Увеличь радиус своего прицела, чтобы видеть и воровать с минимальными усилиями
jazz.weapon.snatcher.upgrade.range=Дистанция кражи
jazz.weapon.snatcher.upgrade.range.desc=Увеличь расстояние, с которого сможешь воровать предметы
jazz.weapon.snatcher.upgrade.auto=Авто-авто прицел
jazz.weapon.snatcher.upgrade.auto.desc=Зажми ЛКМ, чтобы автоматизировать подбор множества пропов обновременно
jazz.weapon.snatcher.upgrade.world=Абсолютный прицел
jazz.weapon.snatcher.upgrade.world.desc=Неважно, куда ты целишься, ты что-то подбираешь. Зажми ПКМ, чтобы воровать браши карты
#'
jazz.weapon.snatcher.upgrade.multi=Многозадачность
jazz.weapon.snatcher.upgrade.multi.desc=Будь многозадачным, воруя браши и пропы одновременно
jazz.weapon.snatcher.upgrade.wspeed=Скорость кражи мира
jazz.weapon.snatcher.upgrade.wspeed.desc=Воруй мир на 100% быстрее
#Hacking Goggles
jazz.weapon.hacker=Взломоочки
jazz.weapon.hacker.desc=Загляните во внутрь работы I/O карты
jazz.weapon.hacker.upgrade.io=Повышение привилегий
jazz.weapon.hacker.upgrade.io.desc=Даёт доступ на запись во Взломоочках для ручной активации I/O событий карты
#Stan
jazz.weapon.stan=Стэн
jazz.weapon.stan.desc=Телепортируйся сквозь стены, браши и невидимые стены, призвав силу Стэна
jazz.weapon.stan.upgrade.range=Радиус
jazz.weapon.stan.upgrade.range.desc=Увеличивает дальность и глубину преодолеваемых стен
jazz.weapon.stan.upgrade.speed=Скорость
jazz.weapon.stan.upgrade.speed.desc=Уменьшает время подготовки
#Run
jazz.weapon.run=Бег
jazz.weapon.run.desc=Прыгай выше и бегай быстрее
jazz.weapon.run.upgrade.nofall=Игнорировать урон от падения
jazz.weapon.run.upgrade.nofall.desc=Упади с любой высоты, и пока экипирован Бег, ты не получишь урон
jazz.weapon.run.upgrade.highjump=Заряженный прыжок
jazz.weapon.run.upgrade.highjump.desc=С экипированным Бегом присядь на пару секунд, чтобы зарядить супер прыжок!
#misc
jazz.weapon.buscaller=Портативная автобусная остановка
jazz.weapon.physlua=Lua Физпушка
#==============================================================================
#	HUD/HUB
#==============================================================================
jazz.hud.money=$%1%
jazz.hud.loading=Загрузка...
jazz.hud.unknown=Неизвестно
jazz.hud.earned=%1% заработал $%2%
jazz.hud.spent=%1% потратил $%2%
jazz.hud.found=%1% нашёл %2% частиц
jazz.hud.kys=Зажми ЛКМ + ПКМ для возрождения
jazz.hud.waiting=ОЖИДАНИЕ ИГРОКОВ
jazz.shards.partial=%1%/%2% частиц
jazz.shards.partialcollected=%1%/%2% частиц собрано
jazz.shards.one=1 частица остался
jazz.shards.none=Ничего не осталось
jazz.shards.all=Собраны все %1% частицы!
jazz.tank.shard=%1% частица
jazz.tank.shards=%1% частиц
jazz.tank.need=нужно %1%
jazz.tank.newgameplus=НИ+ Разблокирована
jazz.leaderboard.patient=САМЫЕ ТЕРПЕЛИВЫЕ
jazz.leaderboard.session=УКРАЛИ НА ЭТОЙ КАРТЕ
jazz.leaderboard.totals=ЛУЧШИЕ ПОХИТИТЕЛИ
jazz.leaderboard.props=%1% пропов
jazz.levelselect.idle=ОЖИДАНИЕ
jazz.levelselect.scan=СКАНИРОВАНИЕ
jazz.levelselect.done=СКАНИРОВАНИЕ ЗАВЕРШЁНО
jazz.levelselect.fail=СБОЙ СКАНИРОВАНИЯ
jazz.levelselect.fail.nomap=СБОЙ СКАНИРОВАНИЯ - В ДОПОЛНЕНИИ НЕТ КАРТ
jazz.levelselect.fail.network=СБОЙ СКАНИРОВАНИЯ - НЕ УДАЛОСЬ СКАЧАТЬ
jazz.levelselect.fail.nospace=СБОЙ СКАНИРОВАНИЯ - ДИСК ПОЛОН
jazz.levelselect.merge=ОБЪЕДИНЕНИЕ МИРОВ
jazz.death.fall=%1% МЁРТВ, упал с большой высоты
jazz.death.self=%1% МЁРТВ, Суицид
jazz.death.killer=%1% МЁРТВ, убит %2%
jazz.death.generic=%1% МЁРТВ, как-то умер
jazz.message.shard=%1% НАШЁЛ частицу
jazz.message.stole=%1% УКРАЛ %2% %3%
jazz.message.brush=браш
jazz.message.brushes=браши
jazz.message.prop=проп
jazz.message.props=пропы
#==============================================================================
#	STORE
#==============================================================================
jazz.store.welcome=С возвращением. Чего желаете?
jazz.store.upgrade=Обновиться!
jazz.store.store=Магазин!
jazz.store.chat=Просто поболтать!
jazz.store.requires=ТРЕБУЕТСЯ %1%
jazz.store.toollabel=Инструменты
jazz.store.upgradelabel=Обновления
#mind the leading and/or trailing space!
jazz.store.listing= %1% - $%2%
jazz.store.price= $%1% 
#==============================================================================
#	MISSIONS
#==============================================================================
jazz.mission.finished=ЗАВЕРШЕНО!!!
jazz.mission.locked=<Недоступно>
#Cellist
jazz.mission.drums=Собрать %1% топливных бочек
jazz.mission.gasbeer=Собрать %1% канистр и пивных бутылок
jazz.mission.chems=Собрать %1% случайных химикатов
jazz.mission.paint=Собрать %1% банок с краской
jazz.mission.drk=Украсть Д-р. Кляйнера
jazz.mission.cactus=Украсть кактус в горшке
#Bartender
jazz.mission.crates=Найти %1% складских коробок
jazz.mission.cars=Добыть %1% машин
jazz.mission.melons=Найти %1% арбузов
jazz.mission.gas=Найти %1% бензобаков
jazz.mission.washers=Найти %1% стиральных машин
jazz.mission.antlions=Найти %1% муравьиных львов
#Pianist
jazz.mission.chairs=Найти %1% стульев
jazz.mission.crabs=Украсть %1% хедкрабов
jazz.mission.meals=Найти %1% вкусных блюд
jazz.mission.vending=Borrow %1% торговых автоматов
jazz.mission.horse=Найти статую лошади
jazz.mission.metropolice=Найти %1% сотрудников ГО
#Singer
jazz.mission.documents=Найти %1% папок с документами
jazz.mission.dolls=Найти %1% игрушечных кукол
jazz.mission.radiators=Найти %1% радиаторов для поддержания тепла
jazz.mission.plants=Найти %1% растений в горшках
jazz.mission.alyx=Украсть Аликс
jazz.mission.radios=Украсть несколько радио
#==============================================================================
#	FACT SCREENS
#==============================================================================
jazz.fact.views=Просмотров:\n%1%
jazz.fact.filesize=Размер файла:\n%1%
jazz.fact.favs=Избранных:\n%1%
jazz.fact.subs=Подписок:\n%1%
jazz.fact.uploaded=Добавлено:\n%1%
jazz.fact.modified=Изменено:\n%1%
jazz.fact.tags=Тэги:\n%1%
jazz.fact.mapsize=Размер карты:\n%1% в ширину\n%2% в глубину\n%3% в высоту
jazz.fact.skybox=Скайбокс:\n%1%
jazz.fact.metadata=Данные карты:\n%1%
jazz.fact.brushes=Брашей:\n%1%
jazz.fact.staticprops=Стат пропов:\n%1%
jazz.fact.entities=Энтити:\n%1%
jazz.fact.map=Карта:\n%1%
jazz.fact.unknown=Неизвестно
jazz.fact.none=Нет
#==============================================================================
#	GAME MODE
#==============================================================================
jazz.gamemode.wait=Дождись игроков в начале уровня
jazz.gamemode.wait.help=Стоит ли вообще включать ожидающих игроков на доске.
jazz.gamemode.localaddons=Включить локальные дополнения в рандомизатор карт
jazz.gamemode.localaddons.help=Если включено, карты из локально установленных дополнений мастерской будут учитываться при выборе карты.